In [3]:
import numpy as np
print(np.__version__)

1.12.1


In [4]:
array=np.array([1,2,3],dtype=np.uint8)
print(array)

[1 2 3]


In [6]:
mat1=np.zeros((2,3))

In [8]:
nd=np.zeros((1,2,3,4))
print (nd.shape)
print(nd.size)

(1, 2, 3, 4)
24


In [9]:
scalar=2
mat=np.ones((2,3))
mat1=scalar*mat

In [11]:
mat=np.zeros((2,3))
tmat=mat.T
print(mat.shape,tmat.shape)
mat3=np.array((1,2,3))
tmat3=mat3.T
print(mat3.shape,tmat3.shape)


(2, 3) (3, 2)
(3,) (3,)


In [14]:
mat1=np.array([[1,2],[3,4]])
mat2=np.array([[5,6],[7,8]])
mat3=mat1+(mat2)

In [15]:
mat3=mat1.dot(mat2)

In [16]:
mat=mat1*mat2#每个元素都相应相乘


In [17]:
mat1=scalar+mat#每个标量加到每个元素上

In [18]:
mat3=np.zeros((1,2,3))
tmat3=mat3.transpose(0,2,1)#将矩阵的维度改变，第0维不变，第2和1维交换
print(mat3.shape,tmat3.shape)

(1, 2, 3) (1, 3, 2)


In [22]:
mat1=np.zeros((3,2))
vec=np.array([[1],[2],[3]])
print(vec)
print(mat1+vec)

[[1]
 [2]
 [3]]
[[ 1.  1.]
 [ 2.  2.]
 [ 3.  3.]]


In [23]:
rannum=np.random.randn(5,10)

In [26]:
l=[1,2,3]
np.random.shuffle(l)
print(l)

[1, 3, 2]


In [28]:
a=np.random.randn(3,2)
print(a)
print(np.sum(a))

[[ 0.82490006  0.18077698]
 [ 0.60256537  1.75333491]
 [-0.62687773  0.13380414]]
2.86850371412


In [29]:
a=np.ones((3,2))
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))


[ 3.  3.]
[ 2.  2.  2.]


In [31]:
a=np.random.randn(3,2)
print(np.exp(a))

[[ 1.17865405  5.15877812]
 [ 0.42142546  0.73683703]
 [ 1.59545823  3.49434084]]


In [32]:
a=[1,2,3,4,3,2,1]
print(np.argmax(a))

3
